### ISSUE TITLE
Background Video CSS

### ISSUE THREAD

**Issue by emerconn** [emerconghaile/emerconghaile.dev#19]
replace the background video transparent black overlay using `header::after`

**Comment by emerconn** [comment]
```css
header::after {
  content: "";
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background: rgba(0, 0, 0, 0.7);
  z-index: -1;
}
```
